language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - pip install -U pip
  - pip install wheel
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
# command to install dependencies
install:
    - "pip wheel -r requirements.txt"
    - "pip install -r requirements.txt"
    - "pip install coveralls"
# command to run tests
script:
    - nosetests --cover-package=tests --with-coverage
#    - python -m unittest discover -s tests -p "*.py" -v
addons:
    code_climate:
        repo_token: f3e88232a9b26c48cbc2de4c2cc0b60faf6e4c43a73ae23bd609db623ff22d52
after_success:
  - bash <(curl -s https://codecov.io/bash)
