language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - pip install -U pip
  - pip install wheel
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
# command to install dependencies
install:
    - "pip wheel -r requirements.txt"
    - "pip install -r requirements.txt"
# command to run tests
script: python -m unittest discover -s tests -p "*.py" -v